### ISSUE TITLE
Connection expiry

### ISSUE THREAD

**Issue by LucasBob** [daybowbow-dev/tower-sessions-libsql-store#3]
Hey there,
Thank's a lot for sharing your work!

I was wondering if you tested this in a project with a remote database. I'm building a product that relies on Turso :heart: and had issues previously with my code (unrelated to your lib) as it looks like the connection closes after a 10s period.
I'm not sure if it's after 10s of inactivity or if it's a hard 10s but you get the idea. It appears we can't just keep a connection open for long, we are supposed to reopen one regularly when querying. 

I was wondering if the deletion of outdated sessions at 7s in your example counters that or if the fact that sessions are invalidated after 10s in the example provided just makes the case never happen in the end... 
Anyways, as it looks to me that 10s would not fit most production usages, I would really love your insights on that one... :+1: 

Thank's again for sharing!
Bob

**Comment by LucasBob** [comment]
Ok, I investigated a little bit on my side on my lunch break and it looks like we can just use the `reset()` function on the `Connection` in order to _revive_ it. It should be pretty easy to move from here, I'll give a try to your solution with that in mind.

In the mean time, I found again the piece of doc that mentions the timeouts in here :smiley_cat: it's kinda hidden at the bottom of that section : https://docs.turso.tech/sdk/http/reference#interactive-query

Please feel free to close this issue if you have nothing to add
Cheers :beers:

**Comment by daybowbow-dev** [comment]
Hi @LucasBob - Good investigation. The numbers I used were arbitrary and low just to show the example quickly. I was not aware of the timeout mentioned, though I haven't used interactive queries as much in my projects.
